### ISSUE TITLE
你好，什么时候出PC版本呀

### ISSUE THREAD

**Issue by Canan666** [JiuRanYa/StandUp#2]
跪求PC版本

**Comment by JiuRanYa** [comment]
@Canan666 ❤️I'll release a pc version today if possible. Thanks!

**Comment by JiuRanYa** [comment]
@Canan666 Hi, I have been released a new version 0.2.0. Now you can download `.exe` from the lasted release.

**Comment by JiuRanYa** [comment]
I don't have a PC device to test it. If there is problem with the app, please give me feedback and I will reopen this issue.
